title: Curriculum
description: プログラミング学習カリキュラム

# GitHub Pagesではremote_themeを使用
remote_theme: just-the-docs/just-the-docs

# ローカルプレビューでは上の行をコメントアウトして、下の行のコメントを外す
# theme: just-the-docs

# 検索を有効化
search_enabled: true

# サイドバーのナビゲーション
nav_external_links:
  - title: GitHub
    url: https://github.com/dik-ab/curriculum

# フッター
back_to_top: true
back_to_top_text: "トップに戻る"

# カラースキーム
color_scheme: light
